# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f6e937177ac348383b552c8a0222328b4d3a68e00690709e5011f6c83f056bd2495fc4ce8d1a366577fdda7622bfe9964e4e3d252900ef1527a3e1dd6c6e62c

test:
  secret_key_base: 9828e8b6b8052ab637b4a79752da97dfc67a08531ffb134a5f9c9b260db82eb3b1bfd450ab3ee3ce569b921bafb19000b55dd39bd7d3919c7b4b048afb5a28be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
